file(GLOB_RECURSE ENGINE_HEADERS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "src/*.h")
file(GLOB_RECURSE ENGINE_SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "src/*.cpp")
file(GLOB_RECURSE GAME_SHADERS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "src/*.glsl")

